// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCedNfPICURURe2Yi8PfJnsSLVXNA5eLjY',
    appId: '1:810776624742:web:ddf0c17479615f932c37a7',
    messagingSenderId: '810776624742',
    projectId: 'carmodel-3dc15',
    authDomain: 'carmodel-3dc15.firebaseapp.com',
    storageBucket: 'carmodel-3dc15.firebasestorage.app',
    measurementId: 'G-N5EZM7Y2MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoHKWWdksMgxR4upCpr-9MnNcox9hCjHE',
    appId: '1:810776624742:android:e708a4b5c1eb9e4a2c37a7',
    messagingSenderId: '810776624742',
    projectId: 'carmodel-3dc15',
    storageBucket: 'carmodel-3dc15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9pQtGiJ1gItnM6jmGQauX7RVaUE72aQc',
    appId: '1:810776624742:ios:bcd41acca38d36f12c37a7',
    messagingSenderId: '810776624742',
    projectId: 'carmodel-3dc15',
    storageBucket: 'carmodel-3dc15.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9pQtGiJ1gItnM6jmGQauX7RVaUE72aQc',
    appId: '1:810776624742:ios:bcd41acca38d36f12c37a7',
    messagingSenderId: '810776624742',
    projectId: 'carmodel-3dc15',
    storageBucket: 'carmodel-3dc15.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCedNfPICURURe2Yi8PfJnsSLVXNA5eLjY',
    appId: '1:810776624742:web:a1d5fbb3d42c48a02c37a7',
    messagingSenderId: '810776624742',
    projectId: 'carmodel-3dc15',
    authDomain: 'carmodel-3dc15.firebaseapp.com',
    storageBucket: 'carmodel-3dc15.firebasestorage.app',
    measurementId: 'G-H7CCELBZ6J',
  );
}
